import cv2
print(cv2.__version__)
original = cv2.imread(r"C:\Users\Welcome\Downloads\text.jpg",cv2.IMREAD_UNCHANGED)
grey=cv2.cvtColor(original ,cv2.COLOR_BGR2GRAY)
hsv=cv2.cvtColor(original ,cv2.COLOR_BGR2HSV)
cv2.imshow("original ",original)
cv2.imshow("grey scale",grey)
cv2.imshow("hsv",hsv)
print('size of original',original.shape)
o2=cv2.resize(original,(400,600))
print('size of new image',o2.shape)
cv2.imshow("resize",o2)
ret,binary_thresh=cv2.threshold(grey,160,255,cv2.THRESH_BINARY)
ret1,binary_inv=cv2.threshold(grey,160,255,cv2.THRESH_BINARY_INV)
original_addaptive=cv2.imread(r"C:\Users\Welcome\Downloads\text.jpg",0)
ret2,Adaptive_thresh_gaussian=cv2.threshold(original_addaptive,160,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C)
ret3,Adaptive_mean_thresh=cv2.threshold(original_addaptive,160,255,cv2.ADAPTIVE_THRESH_MEAN_C)
cv2.imshow('binary thresh',binary_thresh)
cv2.imshow('binary inv',binary_inv)
cv2.imshow('Adaptive thresh gaussian',Adaptive_thresh_gaussian)
cv2.imshow('Adaptive mean tresh',Adaptive_mean_thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()

